### ISSUE TITLE
[Login] OAuth 로그인 UI

### ISSUE THREAD

**Issue by kl204** [1Jo-Survey-Management/survey-management-frontend#2]
OAuth 로그인 화면 UI 입니다

**Comment by MyeoungDev** [comment]
<img width="1440" alt="스크린샷 2023-10-27 오후 2 26 51" src="https://github.com/1Jo-Survey-Management/survey-management-frontend/assets/73057935/d9eb9264-e76f-4d35-b1d4-ac006f69b6e1">

 프론트 쪽에 반응형 다지안이 안되어있고, 아직 회원가입과 로그인이 진행이 안되었는데 `localStorage` 에 `accessToken`이 존재하네요.
 이 부분은 수정해주셔야 될것 같습니다.

**Comment by MyeoungDev** [comment]
<img width="927" alt="스크린샷 2023-10-27 오후 3 12 11" src="https://github.com/1Jo-Survey-Management/survey-management-frontend/assets/73057935/4df1a493-7d13-485c-92b9-9548f47e4635">

위의 회원 가입 페이지에서  뒤로가기를 할 경우 DB에 동일한 데이터가 2개 들어가는 문제가 있습니다.
해결 부탁드립니다.
